[project]
name = "marimo-local-ai-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.17.8",
    "openai>=2.8.1",
    "polars>=1.35.2",
]
